on : push
jobs:
    print-version:
        runs-on : ubuntu-latest
        steps:
             name : Checkout code
             uses: actions/checkout@v2
             name : Install npm
            uses : npm-i
            name : Run test
            run : npm test


           